
jobs:
  - job: Build_Linux
    pool:
      vmImage: 'ubuntu 16.04'
    steps:
      - template: build-template.yml
        parameters:
          url: https://github.com/ldc-developers/ldc/releases/download/v1.13.0/ldc2-1.13.0-linux-x86_64.tar.xz
          bindir: ldc/ldc2-1.13.0-linux-x86_64/bin
          archive: ldc.tar.xz
          binary: dc

  - job: Build_Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: build-template.yml
        parameters:
          url: https://github.com/ldc-developers/ldc/releases/download/v1.13.0/ldc2-1.13.0-windows-x64.7z
          bindir: ldc/ldc2-1.13.0-windows-x64/bin
          archive: ldc.7z
          binary: dc.exe

  - job: Test_Windows
    pool:
      vmImage: 'vs2017-win2016'
    dependsOn: Build_Windows
    steps:
      - template: test-template.yml
        parameters:
          binary: dc.exe

  - job: Test_Linux
    pool:
      vmImage: 'ubuntu 16.04'
    dependsOn: Build_Linux
    steps:
      - template: test-template.yml
        parameters:
          binary: dc
