
jobs:
  - job: Linux
    variables:
      url: https://github.com/ldc-developers/ldc/releases/download/v1.13.0/ldc2-1.13.0-linux-x86_64.tar.xz
      bindir: ldc/ldc2-1.13.0-linux-x86_64/bin
      archive: ldc.tar.xz
    pool:
      vmImage: 'ubuntu 16.04'
    steps:
      - template: build-template.yml
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: dc
          artifactName: binary-linux

  - job: Windows
    variables:
      url: https://github.com/ldc-developers/ldc/releases/download/v1.13.0/ldc2-1.13.0-windows-x64.7z
      bindir: ldc/ldc2-1.13.0-windows-x64/bin
      archive: ldc.7z
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: build-template.yml
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: dc.exe
          artifactName: binary-windows
